version: '2'
services:
  # web with xdebug - actency images
  web:
    # actency/docker-apache-php available tags: latest, 7.0, 5.6, 5.5, 5.4, 5.3
    image: actency/docker-apache-php:5.6
    # actency/docker-nginx-php available tags: latest, 5.6, 5.5, 5.4
    #image: actency/docker-nginx-php:5.6
    ports:
      - "80:80"
      - "9000:9000"
    environment:
      - SERVERNAME=drupal7-composer.loc
      - SERVERALIAS=drupal7-composer.loc
      - DOCUMENTROOT=web
    volumes:
      - /home/docker/projets/drupal7-composer:/var/www/html/
      # - /c/Users/your_ssh_keys/:/var/www/.ssh/
    links:
      - database:mysql
      - mailhog
      - memcache
      - solr
    tty: true

  # database container - actency images
  database:
    # actency/docker-mysql available tags: latest, 5.7, 5.6, 5.5
    image: actency/docker-mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlroot
      - MYSQL_DATABASE=drupal7-composer
      - MYSQL_USER=drupal7-composer
      - MYSQL_PASSWORD=mysqlpwd
    #volumes:
      #- /my/custom:/etc/mysql/conf.d/

  # phpmyadmin container - actency images
  phpmyadmin:
    image: actency/docker-phpmyadmin
    ports:
      - "8010:80"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlroot
      - UPLOAD_SIZE=1G
    links:
      - database:mysql

  # mailhog container - official images
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  # memcache container - official images
  memcache:
    image: memcached
    ports:
      - "11211:11211"
    command: memcached -m 64

  # solr container - actency images
  solr:
    # actency/docker-solr available tags: latest, 5.5, 5.4, 5.3, 5.2, 5.1, 5.0, 4.10, 3.6
    image: actency/docker-solr:latest
    ports:
      - "8080:8983"